src/Entity/OrderDetails.php
<?php

namespace App\Entity;

use App\Repository\OrderDetailsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderDetailsRepository::class)]
class OrderDetails
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orderDetails')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $id_order = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $id_menu = null;

    #[ORM\ManyToOne(inversedBy: 'orderDetails')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $id_product = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $quantity = null;

    #[ORM\Column]
    private ?float $total = null;

    #[ORM\ManyToOne(inversedBy: 'orderDetails')]
    private ?Menu $menu = null;

    public function __toString(){
        return $this->getIdProduct().' x'.$this->getQuantity();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdOrder(): ?Order
    {
        return $this->id_order;
    }

    public function setIdOrder(?Order $id_order): self
    {
        $this->id_order = $id_order;

        return $this;
    }

    public function getIdMenu(): ?string
    {
        return $this->id_menu;
    }

    public function setIdMenu(?string $id_menu): self
    {
        $this->id_menu = $id_menu;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->id_product;
    }

    public function setIdProduct(?Product $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(float $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getMenu(): ?Menu
    {
        return $this->menu;
    }

    public function setMenu(?Menu $menu): self
    {
        $this->menu = $menu;

        return $this;
    }
}

src/Controller/OrderSuccessController.php
<?php

namespace App\Controller;

use App\Classes\Mail;
use App\Classes\Cart;
use App\Entity\Loyalty;
use App\Entity\Order;
use App\Entity\Product;
use App\Entity\User;
use Dompdf\Dompdf;
use Dompdf\Options;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class OrderSuccessController extends AbstractController
{

    private $entityManager;
    private $session;

    public function __construct(EntityManagerInterface $entityManager, SessionInterface $session){
        $this->entityManager = $entityManager;
        $this->session = $session;
    }

    #[Route('/commande/merci/{stripeSessionId}', name: 'order_success')]
    public function index($stripeSessionId, Cart $cart, ): Response
    {

        $order = $this->entityManager->getRepository(Order::class)->findOneByStripeSessionId($stripeSessionId);

        // dd($order);

        if (!$order || $order->getUser() != $this->getUser()) {
            return $this->redirectToRoute('home');
        }
        
        

        if ($order->getState() == 0) {
                $user = $this->getUser();
                $points = $user->getPoints();
                $total = $order->getTotal();
                $total = $total/100;
                $points = ($points + $total);
                $user->setPoints($points);

            $points = $this->session->get('points', []);
             if($points != null){
             foreach ($this->session->get('points', []) as $slug => $quantity) {
                $product_full = $this->entityManager->getRepository(Product::class)->findOneBySlug($slug);
                $user = $this->getUser();
                $points = $user->getPoints();
                $points_object = $this->entityManager->getRepository(Loyalty::class)->findOneByProduct($product_full);
                if($points_object->getNumberPoints() == 0){
                    $test = 15;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 1){
                    $test = 30;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 2){
                    $test = 60;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 3){
                    $test = 90;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
            }
                $user->setPoints(round($points));
                $this->entityManager->persist($user);
                $this->entityManager->flush();
        }





            $cart->remove();
            $this->session->set('list_item', null);
            $this->session->set('points', null); 

            $order->setState(1);
            $this->entityManager->flush();
            $userAdmin = $this->entityManager->getRepository(User::class)->findAll();





            $mail = new Mail();
            $content = "Bonjour ".$order->getuser()->getFirstName()."<br> Merci pour votre commande.<br> ";
            $mail->send($order->getUser()->getEmail(), $order->getUser()->getFirstName(), 'Votre commande McKing est bien validée', 'Commande chez McKing', $content);
            
            $adminEmail = [];

            foreach ($userAdmin as $value) {
                foreach ($value->getRoles() as $role) {
                   if ($role == "ROLE_ADMIN") {
                    $adminEmail[] = [$value->getEmail()];
                } 
                }
            }
            foreach ($adminEmail as $value) {
                foreach ($value as $email) {
                    $mailAdmin = new Mail();
                    $contentAdmin = "La commande ".$order->getReference()." a été validée, veuillez la préparer";
                    $mailAdmin->send($email, $order->getUser()->getFirstName(), 'Votre commande McKing est bien validée', 'Commande chez McKing', $contentAdmin);
                }
                
            }
            
        }

        return $this->render('order_success/index.html.twig', [
            'order' => $order
        ]);
    }

    #[Route('/commande/valider/{id}', name: 'order_success_loyalty')]
    public function show($id): Response
    {

        $order = $this->entityManager->getRepository(Order::class)->findOneById($id);

        if (!$order || $order->getUser() != $this->getUser()) {
            return $this->redirectToRoute('home');
        }

        if ($order->getState() == 0) {

            $points = $this->session->get('points', []);
             if($points != null){
             foreach ($this->session->get('points', []) as $slug => $quantity) {
                $product_full = $this->entityManager->getRepository(Product::class)->findOneBySlug($slug);
                $user = $this->getUser();
                $points = $user->getPoints();
                $points_object = $this->entityManager->getRepository(Loyalty::class)->findOneByProduct($product_full);
                if($points_object->getNumberPoints() == 0){
                    $test = 15;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 1){
                    $test = 30;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 2){
                    $test = 60;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
                elseif($points_object->getNumberPoints() == 3){
                    $test = 90;
                    $points = ($points - $test);
                    $user->setPoints($points);
                }
            }
                $user->setPoints(round($points));
                $this->entityManager->persist($user);
                $this->entityManager->flush();
        }


            $this->session->set('points', null);

            $order->setState(1);
            $this->entityManager->flush();

            $mail = new Mail();
            $content = "Bonjour ".$order->getuser()->getFirstName()."<br> Merci pour votre commande.<br>";
            $mail->send($order->getUser()->getEmail(), $order->getUser()->getFirstName(), 'Votre commande McKing est bien validée', 'Commande chez McKing', $content);
            
            $userAdmin = $this->entityManager->getRepository(User::class)->findAll();
            $adminEmail = [];

            foreach ($userAdmin as $value) {
                foreach ($value->getRoles() as $role) {
                   if ($role == "ROLE_ADMIN") {
                    $adminEmail[] = [$value->getEmail()];
                } 
                }
            }
            foreach ($adminEmail as $value) {
                foreach ($value as $email) {
                    $mailAdmin = new Mail();
                    $contentAdmin = "La commande ".$order->getReference()." a été validée, veuillez la préparer";
                    $mailAdmin->send($email, $order->getUser()->getFirstName(), 'Votre commande McKing est bien validée', 'Commande chez McKing', $contentAdmin);
                }
        }
    }
        return $this->render('order_success/index.html.twig', [
            'order' => $order
        ]);
    }
    
}

templates/order_success/facture.html.twig
	<style type="text/css">
                <!--  table
                {
                        width: 100%;
                        border-collapse:collapse;
                font-size:16px}
 
 
                .header td
                {
                        width: 50%;
                vertical-align: top}
 
 
                .text-left
                {
                text-align: left}
 
 
                .text-right
                {
                text-align: right}
 
 
                .text-center
                {
                text-align: center}
 
 
                .separator
                {
                        height: 20px;
                width: 100%}
 
 
                .content td
                {
                        border:solid 1px #CFD1D2;
                        padding: 5px;
                }
 
 
                .content th
                {
                        border:solid 1px #000000;
                        padding: 5px;
                        background-color: #000000;
                color: #FFFFFF}
 
 
                .ligne1Content
                {
                background-color:#57B223}
 
 
                .couleurgris
                {
                        background-color:#DDDDDD;
                        height:auto;
                }
 
 
                .tht, .taxe, .ttc
                {
                        font-size: 1.2em;
                }
 
 
                .ttc
                {
                        color:#E31B00;
                        font-weight:bold;
                }
 
 
                .couleurverte
                {
                background-color: #E31B00}
 
 
                .couleurmoinsgris
                {
                        background: #EEEEEE;
                }
 
 
                .taille1
                {
                        width:40%;
                }
                .taille6{
                    width:100%;
                }
 
                .taille2
                {
                        width:15%;
                }
 
 
                .taille3
                {
                        width:15%;
                }
 
 
                .taille4
                {
                        width:20%;
                }
 
 
                .taille5
                {
                        width:10%;
                }
 
 
                .header1
                {
                width:50%}
 
 
                .header2
                {
                width:50%}
 
 
                .tailleligne
                {
                        height:auto;
                }
 
 
                .taille1, taille2, taille3, taille4, taille5
                {
                        height:auto;
                }
 
 
                span
                {
                        font-size:14px;
                        font-weight:bold;
                        color:#E31B00;
                }
 
 
                h1, h2, h3
                {
                        color:#E31B00;
                }
 
 
                .colorwhite
                {
                color:white}
        </style>
	<table class="header">
		<tr>
			<td class="text-lef">
				<h1>Facture</h1>
				<br>
			</td>
		</tr>
		<tr>
			<td class="text-left">
				<span>DE :</span>
				
				McKing {{order.city.city}}
				<br>
			</td>
			<td class="text-right">
				<span>FACTURE N°:</span>
				 {{ order.reference }}
				<br/>
				<br/>
				<span>DATE: </span>
				{{ order.date|date('d-m-Y') }}
				<br/>
			</td>
		</tr>
		<tr>
			<td class="text-left">
				<br/>
				<br/>
		
				<br/>
				<br/>
				<span>FACTURÉ À :</span>
                

				{{order.user.firstname}} {{order.user.lastname}}
				<br>
                <br/>
				<br/>
			</td>
			<td class="text-right"></td>
		</tr>
	</table>
	<table class="content">
		<tbody>


{% set menuid = 0 %}
{% for orderDetails in orderDetails %}
          <tr>

                    {% if orderDetails.idMenu == null %}
                   <td colspan="4" class="text-center ">{{ orderDetails.idProduct.name }}</td>
                   {% if order.stripeSessionId != null %}
                        {% if orderDetails.price == 0 %}
                                <td class="text-center ">Offert</td>
                                {% else %}
                                <td class="text-center ">{{ (orderDetails.idProduct.price / 100)|number_format(2, ',', '.') }}€</td>
                                {% endif %}
                   {% elseif order.stripeSessionId == null %}
                        <td class="text-center ">Offert</td>
                   {% endif %}
                        {% else %}
                                {% if menuid == orderDetails.idMenu %}         
                                {% else %}
                                {% set menuid = orderDetails.idMenu %}
                                <td colspan="4" class="text-center"> Menu {{orderDetails.menu.name}} - {{ orderDetails.idProduct.name }} </td>
                                        {% if orderDetails.menu.id == '1' %}
                                <td class="text-center ">{{ ((orderDetails.idProduct.price + 330)/ 100 )|number_format(2, ',', '.') }}€</td>
                                        {% elseif orderDetails.menu.id == '2' %}
                                <td class="text-center ">{{ ((orderDetails.idProduct.price + 380 )/ 100)|number_format(2, ',', '.') }}€</td>
                                        {% elseif orderDetails.menu.id == '3' %}
                                <td class="text-center ">{{ ((orderDetails.idProduct.price + 580) / 100)|number_format(2, ',', '.') }}€</td>
                                        {% elseif orderDetails.menu.id == '4' %}
                                <td class="text-center ">{{ (428 / 100)|number_format(2, ',', '.') }}€</td>
                                        {% endif %}
                                {% endif %}
                        {% endif %}     
                    
     
              </tr>      
            {% endfor %}

		
 
 
		</tbody>
		<tfoot>
	
			<tr>
				<td colspan="4" class="text-center">
					<h3>TOTAL TTC À PAYER</h3>
				</td>
				<td class="text-center">
					<h3> {{ (order.total / 100)|number_format(2, ',', '.') }}€</h3>
				</td>
			</tr>
		</tfoot>
	</table>

templates/order_success/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirmation de commande - McKing{% endblock %}
{% block headerProduct %}
{% endblock %}

{% block content %}
    {# {{ dump(order) }} #}

    <div class="contour2">
    <div class="logo-loyalty">
        <img src="{{ asset('assets/images/Logo.svg') }}" alt="Logo McKing">
    </div>
    <div class="confirm-content">
        <h1>Confirmation de commande</h1>
        <p><strong>{{ order.user.firstname }}</strong>
        <br>
        Votre commande n°<strong>{{ order.reference }}</strong> à bien été prise en compte.
        </p>
        <hr>
        {% if order.stripeSessionId != null %}
            <p><a href="{{ path('facture', { stripeSessionId: order.stripeSessionId }) }}">Télécharger votre facture</a></p>
        {% else %}
            <p><a href="{{ path('facture_id', { id: order.id }) }}">Télécharger votre facture</a></p>
        {% endif %}
        
        
        <hr>
        <p>Vous trouverez l'historique de vos commandes dans votre espace <a href="{{ path('account') }}">compte</a>.</p>

        <div class="return-home">
        <a href="{{ path('home') }}">Retourner à l'accueil</a>
        </div>
    </div>
    </div>
{% endblock %}

{% block navBar %}

{% endblock %}